# Generated by Django 6.0.3 on 2026-04-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_user_id", models.CharField(max_length=64)),
                ("student_id", models.CharField(blank=True, max_length=16, null=True)),
                ("email", models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
