# Generated by Django 6.0.3 on 2026-05-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_VERIFICATION", "Pending Verification"),
                    ("VERIFIED", "Verified"),
                ],
                default="PENDING_VERIFICATION",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
